lib/ready.js
A few themes:
* Reframing from the Kite autocomplete daemon -> Kite Menubar app.  The thinking was 'daemon' sounds too technical, and we want to use common wording across e.g. the Menubar menu and these notifications.
* I tried to make the heading text shorter, and more like a title.
* My main concern was with the whitelist copy, which I made similar to what we currently have for that in the sidebar.
=> Updated copy for notification text

README.md, lib/completions.js, lib/elements/login.js, lib/events.js, lib/kite.js, lib/metrics.js, lib/ready.js, lib/utils.js, package.json
This pr changes the kite plugin to check whether the current dir is whitelisted by checking the HTTP response code from the `/clientapi/editor/event` endpoint.
It also makes the following more minor changes:
- clicking a button in a notification does not trigger the one hour lockout for that notification.
- do not show launch error if the error was that kite is already running, and similarly for other errors
- bump up completions priority so that it always supercedes autocomplete-python
- add a "Reset password" button to the login UI
=> check whether the current dir is whitelisted when sending events to kited

lib/ready.js
Ref #21 
Note that if the user has set the autocomplete-python engine to kite, even if the notification don’t show up, the engine choice form still kicks in.
=> Don't display notification if Kite was uninstalled by the user

lib/ready.js
The notification now looks like this: 
When choosing `browse` the user is presented with a native dialog to pick a directory to whitelist.
=> Allow to choose the root (homedir or /) or to pick a directory

styles/kite-expand.less
@abe33 cc @adamsmith 
Just some quick sizing tweaks, scaling down of padding, and converting some `px` units to `em` so they inherit font size from parent `kite-expand`.
=> Quick size tweaks

lib/data-loader.js, lib/elements/kite-curated-example.js, lib/elements/kite-expand-function.js, lib/elements/kite-expand-instance.js, lib/elements/kite-expand-module.js, lib/kite-editor.js, lib/kite.js, lib/overlay-manager.js, lib/rollbar-reporter.js, lib/urls.js, lib/utils.js, spec/fixtures/sample.py, spec/overlay-manager-spec.js
Implement contextual menu for tokens:
- Partial support. Given that we have to hit the report endpoint to get the definition we can't be sure we'll have a definition to go to.
- [ ] Usages
- As of today (version of the 15-02) I still get 404 for every requests I make to this endpoint so the menu still does nothing.
=> Context menu

lib/elements/kite-signature.js
@abe33 this pr makes a slight modification to the gating for the common invocations section. 
All users are allowed to see the call signature and this is indicated via the `call_signatures_*` flags. 
Only pro users are allowed to see the "Popular Patterns" section and this is indicated via the `common_invocations_*` flags.
Sorry for all the thrashing around this! We changed the naming up last Friday, I have accidentally been referring to this as "Call Signatures" in the docs, my bad! I have updated all of the relevant docs!
=> Gate common invocations

lib/elements/html-utils.js
This is a bit convoluted of a solution, but it should cover pretty much all cases, as a quick patch. I'll look for a nicer solution later.
Ref #261
=> Fix access to id when rendering additional examples link

lib/kite.js, lib/metrics.js, package.json
This PR implements the `kited_health` metric sent to Segment. 
The switch between development and production mode is done using the `inDevMode` helper of the Atom APIs. 
No events are sent when running tests.
The `userId` field can't be `0` as it seems the nodejs lib is validating it, `'0'` makes the validation pass.
=> Implement kited health segment metrics

lib/completions.js
Apparently there's an issue with bracket matcher that makes the position
we receive in the autocomplete-plus provider invalid.
=> Use the current editor cursor position instead of the provided one

lib/elements/kite-status-panel.js, lib/notifications-center.js, package-lock.json
@abe33
My first PR!
Going through settings when you install something is a nice entry point/vector of discovery of what that something can do, and I think it’d be nice to have it here.
Changes:
· Add a link to Kite Atom package settings page (URI as per https://github.com/atom/settings-view/pull/1011)
· Make capitalization consistent
· Separate Settings/Help from options coming before for a bit of a better visual hierarchy
Before:
After:
Follow-up work:
· Figure out whether it’s possible to close the pop-up the moment you click a link
· Simplify [this page](https://help.kite.com/category/43-atom-integration) by rewriting “Configuring the Atom plugin” and putting it inside the other section
=> Add a link to Atom package settings in the little Kite bottom menu.

lib/elements/kite-signature.js
As Atom was the only editor to show it and we're not sure at the moment if we should display the linkor not.
=> Remove signature def link

lib/kite-editor.js
The changes look complex but in practice the only significant change is to return a `Promise.all` instead of chaining the autocorrect request after the save validation one.
=> Make save validation and autocorrect requests concurrent

lib/elements/kite-status.js, lib/kite-app.js, lib/kite.js, lib/notifications-center.js, spec/notifications-center-spec.js
When kited restarts (due to an update or whatever) and Atom is running, Atom will continue to poll kited. There are gaps between when kited starts, when it has registered all of its handlers, and lastly when it has restored the user ref from a previous session, should one exist. The user-facing effect are confusing false notifications of Kite state
This PR creates logic to only show `REACHABLE` and `RUNNING` notifications after the state has been confirmed by a re-poll, in order to allow kited sufficient time
=> Fix for false positive notifications

lib/elements/kite-expand-function.js, lib/elements/kite-expand-instance.js, lib/elements/kite-expand-module.js
Closes #332 
Just like the VSCode version, the HTML helpers and styles are still present, let me know if I should remove them.
=> Remove render of SO links in sidebar

styles/kite-autocorrect-sidebar.less
@abe33 + @dbratz1177 
This should do a better job picking the right text colors for showing code in autocorrect. It should support dark themes much better.
Next step would be to grab the font/font size/line spacing from the editor and propagate it here. @dbratz1177 and I talked about one way to do this, but it involves JavaScript.
We can also easily the theme remove/insert colours to always be red and green if we so desire. (GitHub plugin does that.)
Some examples:
Before:
After:
Before:
After:
Before:
After:
Before:
After:
Before:
After:
Before:
After:
=> Better autocorrect insert/delete colors.

lib/elements/kite-autocorrect-sidebar.js, lib/elements/kite-sidebar.js, lib/kite.js, package.json, spec/autocorrect-spec.js, styles/kite-sidebar.less
This PR basically remove the setting and use the dock API version wherever we were switching behavior based on that setting. Also, the sidebars no longer have a close button nor a resizer as we're letting the dock handles that for us.
=> Remove legacy sidebar implementation in favor of the dock API

lib/overlay-manager.js
It prevents atom notifications to kick in.
=> Catch virtual cursor errors in the promise

styles/kite-autocorrect-sidebar.less
@abe33 /cc @dbratz1177 
Instead of stretching the before/after lines into infinity, wrap the line so that the user can actually see what change we’ve done if that change is farther to the right.
Currently, the 2nd/3rd/xth lines will be indented by 4 characters. Once this PR is merged –  https://github.com/kiteco/atom-plugin/pull/346 – we can make it better by using “2 * current indentation” instead of 4 instead.
Before:
After:
=> Make long autocorrect lines better.

lib/elements/kite-autocorrect-sidebar.js, styles/kite-autocorrect-sidebar.less
@abe33 
Nicer style for headers, adds a header for the “history” section.
This header style should eventually be unified with headers in the regular panel.
New style:
=> Nicer headers.

lib/elements/kite-autocorrect-sidebar.js, spec/autocorrect-spec.js
@abe33
Should make it less confusing as you move between the files and keep the pane open.
=> Add a better empty state for when autocorrect haven't made any changes yet.

lib/elements/kite-autocorrect-sidebar.js, styles/kite-autocorrect-sidebar.less
@abe33
· replace tooltips when you hover over thumbs up/down to be nicer and quicker
· add post-click feedback, too
· move thumbs up/down to the help
· style thumbs up/down to be less prominent
=> Better feedback.

lib/elements/kite-autocorrect-sidebar.js, lib/kite.js, styles/kite-autocorrect-sidebar.less
@abe33 /cc @dbratz1177 
This is a pretty naïve way of doing this. I can imagine in the future this needs to be extended to cover all the panels (and also react in real time when user makes changes to these fonts).
However, I’m also interested in getting this in for autocorrect first, to see if we get any feedback on this.
Let me know if this needs to be structured better or placed elsewhere even for MVP.
Before, generic font:
After, exactly the font I use for editing:
=> Makes autocorrect pane use user’s code fonts.

lib/data-loader.js, lib/elements/kite-status.js, lib/gestures/base.js, lib/gestures/click.js, lib/gestures/cursor-move.js, lib/gestures/hover.js, lib/gestures/keyboard.js, lib/gestures/mouse-event.js, lib/gestures/word-hover.js, lib/gestures/word-selection.js, lib/kite-editor.js, lib/kite.js, lib/modes/hyperclick.js, spec/autocorrect-spec.js, spec/gestures/click-spec.js, spec/gestures/cursor-move-spec.js, spec/gestures/hover-spec.js, spec/gestures/keyboard-spec.js, spec/gestures/word-selection-spec.js, spec/spec-helpers.js
Ref kiteco/kiteco#5451
I think hyperclick and context menus are too complex to solve right now, it'd be preferable to remove them and ship these changes and then devise a new strategy to put them back.
=> Remove use of tokens endpoint

lib/completions.js
Changes conditions where `signatures` are triggered
Prior, they would be triggered in e.g. `json.dumps()` on edits w/in the `dumps` and prior to the period (and would always yield a `404`)
The idea with this is to only trigger `signatures` with keystrokes between the parens, reducing `404`s
cc: @tarakju
=> fix for signature triggering

lib/completions.js, lib/editor-events.js, spec/editor-events-spec.js
adds checks to eliminate `clientapi/editor/[event | signature | completion]` calls for non-whitelisted python files
cc: @tarakju 
should eliminate a number of `403`s to those endpoints
NB: I added a quick and somewhat dirty hack to get the tests to pass for this. Would love to do it in a cleaner way, but this seemed by far the simplest way to do so
=> no event, completion, or sig hit for non-whitelisted files

lib/elements/kite-autocorrect-sidebar.js, lib/kite-editor.js, lib/kite.js, spec/autocorrect-spec.js, styles/kite-autocorrect-sidebar.less
=> Swap autocorrect new model icon to blue info icon from a red exclamation point icon.

lib/constants.js, lib/elements/kite-autocorrect-sidebar.js, lib/kite-editor.js, lib/kite.js, package.json, spec/autocorrect-spec.js
@dbratz1177 
Tested by using them, and by verifying that toggling both options in Kite sidebar also toggles them in the settings.
=> Rename commands leading to error rescue.

lib/kite-editor.js, spec/autocorrect-spec.js
@dbratz1177 
[NOT LAUNCH-BLOCKING]
· change string to Error Rescue
· open autocorrect sidebar instead of going to a help doc
=> Fixes for autocorrect new model notification.

lib/elements/kite-autocorrect-sidebar.js, styles/kite-autocorrect-sidebar.less
@dbratz1177 
[NOT LAUNCH-BLOCKING]
…so that only the current one is prominent.
Examples with different themes:
=> Change AutoCorrect diff colours.

lib/elements/navigable-panel.js
@dhung09 
I think this would make it clearer that the keystroke was registered, but Kite has nothing to say… open to other approaches, though?
See: https://github.com/kiteco/kiteco/issues/5650
=> Beep whenever Docs At Cursor are invoked at an invalid place.

lib/kite-data-utils.js, spec/elements/kite-expand-function-spec.js
@abe33
Adds syntax highlighting so it’s consistently applied in different places in the plugin.
This is the most versatile I could make it – using Highlighter for as much as necessary, and not ever relying on saying “python.” Would welcome any suggestions if you have on how to make it simpler.
Please note that “true” and “false” are not highlighted properly because of this bug: https://github.com/kiteco/kiteco/issues/5616
PS I don’t know why the test is failing. I spent half an hour looking at it, but I’m not sure if it’s a failure or something specific with the test?
Before:
After:
Before:
After:
=> Add syntax highlighting to places where it's missing.

lib/elements/kite-status-panel.js
There was a missing double quote breaking the link markup.
=> Fix status panel settings link

lib/kite-editor.js
@dhung09 + @dbratz1177 
This hides hover pop-up whenever the cursor moves (and/or the programmer starts typing).
The rationale here is that the hover might be in the way as you type, obscuring your view. (The same logic that explains why Mac OS hides a mouse pointer the moment you start typing.)
Since there is nothing in the hover the programmer would want to type _from,_ I feel there is no downside.
Also, should I try to add a test for this?
=> Hide hovers when cursor moves.

lib/elements/function-utils.js, lib/elements/html-utils.js, lib/elements/kite-hover.js, lib/elements/kite-signature.js, spec/elements/kite-hover-spec.js, styles/content.less, styles/kite-hover.less
@dbratz1177 
· Don’t allow the hover to grow too wide since it looks awkward
· Break the hover name on dots as we do in sidebar, and allow it to be broken by the browser
· Allow the sidebar name to be broken by the browser
=> Better handling of long names in hover and sidebar.

styles/content.less, styles/kite-error-rescue-sidebar.less, styles/syntax-highlighting.less
@dbratz1177 
As discussed in a meeting a while back.
After:
· https://github.com/kiteco/atom-plugin/pull/340
· https://github.com/kiteco/atom-plugin/pull/389
· https://github.com/kiteco/kiteco/issues/5735
this finalized syntax highlighting for Atom.
More info/discussion: https://kite.quip.com/ZWgsAdvh9xDq/Syntax-highlighting-in-Atom-Implementation-notes-April-2018
=> Switch Error Rescue color to syntax color + add synthesized syntax color for contrast themes.

lib/elements/function-utils.js
=> Remove soft spaces from one area where syntax highlighting is used.

lib/kite-data-utils.js
This is blocking a fix to an important issue with hover not working for top-level packages; that fix changes the ID format slightly. Regardless, this check should no longer be necessary, as we should always return `""` from the API for invalid IDs.
cc @jlozano
=> idIsEmpty should not rely on the string contents

lib/data-loader.js
Several part of the plugin can triggers updates of the status bar, which 
will lead to request to the status endpoint. To avoid 3-4 requests in a 
row the first one is stored until receiving the response and shared if 
another request is triggered in the meantime
Closes #445
=> Memoize getStatus promise to avoid spamming the endpoint

styles/kite-status.less
Apparently, our syncing logo, as not displayed initially, was rendered 
using a 0 width and height, making it invisible.
Closes #434
=> Fix logo flicker when syncing status is displayed

lib/kite-app.js, lib/notifications-center.js
Currently this PR doesn't include the kite-installer package bump, as the change only imply to check a local storage value. By using `localStorage.setItem('kite.no-admin-privileges', true)` you can easily emulate the `kite-installer` behaviour for when we've detected the user had no admin privileges.
Once the kite-installer PR would be approved, merged and released I'll update this PR.
=> Add admin check

lib/elements/kite-status-panel.js
The second `class` attribute with the `account-dependent` class was ignored and the link was active when it shouldn't have.
Fixes #500
=> Fix double classes definition in link

lib/completions.js, lib/data-loader.js, lib/kite.js, styles/kite-signature.less, styles/kite.less
Includes the changes discussed in the quip docs.
=> Move documentation above signature

lib/data-loader.js
HTML examples in the documentation are not escaped, leading to invalid 
display.
=> Use and escape text documentation instead of html

README.md, lib/kite.js, lib/notifications-center.js, package.json
dependent on https://github.com/kiteco/kiteco/pull/6656 and https://github.com/kiteco/kite-api-js/pull/6 getting merged first
This adds the `Kite: Tutorial` feature for interactive onboarding. This will eventually replicated in other editors, and will be also eventually started via the Copilot at the end of onboarding
=> adds kite: tutorial abilities

lib/kite.js, package.json
updates to handle `KITE_LOCAL` vs. non-`KITE_LOCAL` case
relies on https://github.com/kiteco/kite-api-js/pull/10, so will have to change `package.json` accordingly when that's merged
=> updates atom live onboarding

lib/completions.js, lib/kite.js, spec/signature-plus-completions-spec.js
By hacking on the hide suggestion list and cursor moved functions we 
need to account for the response of the signature endpoint to properly 
hide the list when there's no signature data and no suggestions.
Fixes #522
=> Close suggestions on signature request ending with no data

.travis.yml, lib/editor-events.js, package.json, spec/json-runner-spec.js, spec/json/actions/open.js, spec/json/expectations/request.js, spec/json/expectations/request_count.js, spec/json/utils.js, spec/signature-plus-completions-spec.js
Includes changing the `request` and `request_count` expectation to hit the request history endpoint and enabling the live testing using a `LIVE_ENVIRONMENT` variable.
I had to deactivate an unrelated test to get the build pass. I'll look into this later.
=> Implement support for kited-test

lib/completions.js, lib/editors.js, lib/elements/kite-links.js, lib/elements/kite-status-panel.js, lib/elements/kite-status.js, lib/kite-app.js, lib/kite-editor.js, lib/kite.js, lib/notifications-center.js, spec/editors-spec.js, spec/elements/kite-links-spec.js, spec/elements/kite-status-spec.js, spec/json/actions/new_file.js, spec/json/actions/open.js, spec/json/actions/request_hover.js, spec/kite-spec.js, spec/notifications-center-spec.js, spec/signature-plus-completions-spec.js
This pull request introduces a new module that encapsulates the management of Atom's text editors. 
This module now regroups functions that were splitted between the main module and the app object. 
Some parts are still messy  (i.e. when accessing the editors modules through the kite property of the app object in the status) and at the moment the `KiteEditor` class does too little and can problably be merged with the `EditorEvents` one so as to have only one object listening to editor's events, but that will be the scope of next PRs.
=> Refactor kite editors management

lib/elements/kite-signature.js
This solves the issue of not resetting the maximum visible items in completions once the signature is no longer visible
=> Don't expect a parent node to reset the suggestions list limit

lib/kite.js, package.json
The [original](https://github.com/kiteco/atom-plugin/pull/449/files#diff-8cdc4f637889aec27a6a8f6913f34c93R832) fix implementation was lacking in a tricky way. The method implemented there was sufficient to patch up the problem, but due to the binding of `autocomplete-plus`'s source implementation [here](https://github.com/atom/autocomplete-plus/blob/master/lib/autocomplete-manager.js#L106), the use of the patched method on text changes wouldn't actually go into effect until `updateCurrentEditor` was called. This was tricky to catch in development, because the conditions it required to reproduce required that, among perhaps other conditions, the editor not be changed or refreshed.
To test, you can use the new script I defined in `package.json`. IE run `npm run clean-dev-install` to set up …
=> fixes #448; adds helpful dev script command

lib/elements/kite-hover.js, lib/kite-editor.js, lib/overlay-manager.js, styles/kite-links.less
Does two things around hover in Atom
1. Adds an icon to `def` in the Hover (I also toned down icon color intensity). I considered ultimately three icons (and would like further input):
a. unicode &#8619;
My personal favorite - I think the loop in conjunction with the arrow effectively communicates that one is "traveling" within the editor screen to get to something connected with the `def` of the hovered token
b. unicode &#10550; 
A little more "standard" looking than the looping arrow
c. unicode &#167;    
the [symbol](https://en.wikipedia.org/wiki/Section_sign) has decently close established semantics to what our `def` means. But established semantics does always imply common user interpretation
2. Does a bit of reconfiguring to the mechanics of showing/hiding a hover. I increased the …
=> Minor fixes

lib/kite.js
From QA: (May also fix https://github.com/kiteco/kiteco/issues/8056)
> type json.dumps()
> remove ()
> type (
> it will autofill "json.dumps()" but won't give info
This was something I erroneously added while implementing snippets.
=> Fix signatures not appearing after backspacing

lib/kite-data-utils.js, lib/kite.js
- Adds a tab stop at the end of a snippet string. I.e. at `foobar(|)`, hitting tab will move the cursor to `foobar()|`
- Fixes issue where a user has to tab multiple times to move to the next snippet tab stop.
=> Snippets tab fixes

lib/kite.js
Fixes https://github.com/kiteco/kiteco/issues/8115
Previously, we get suggestions then go to the next/previous tab stop, causing a race condition in which snippets prevents autocomplete-plus from displaying completions.
To address this, I took the code from the original snippets [codebase](https://github.com/atom/snippets/blob/master/lib/snippets.js#L536) and overrode it s.t. we fetch suggestions after snippets moves to a different tab stop.
=> Fix for suggestions not appearing after a tab stop

lib/kite.js
Tighten condition for using custom text insertion logic so that in addition to snippets being enabled, the suggestion must have class name 'kite-completion'.
=> Fix Autocomplete For Non-Kite Suggestions

lib/kite.js
Fixes https://github.com/kiteco/kiteco/issues/8713
In the case where there's one snippet, `expansions` contains one item. If there are nested snippets, the most recently added snippet is the last item in the list.
However, being able to tab out of a nested snippet into the original snippet is not in scope for this PR, since the Atom Snippets package itself doesn't support that behavior.
=> Fix tabbing behavior within a nested snippet

lib/kite.js
fixes #631 
It doesn't appear that the StackOverflow search experience is significantly degraded without "scroll past end" enabled, based on my testing.
The alternative is to suggest that the user disable it via a dismissable notification.
=> don't force scroll past end

dist/main.js, lib/bracket-marker.js, lib/kite.js
Fixes https://github.com/kiteco/kiteco/issues/10318
The `BracketTracker` class reads selected kite completions to check for closing brackets and hooks into `editor.onWillInsertText` to check whether a user would like to insert a closing bracket at a location that should write-through.
This behavior of navigating away, navigating back in, then still writing through is consistent with the default (shipped with the Atom IDE) `bracket-matcher` package behavior.
Check behavior is like that of the GIF for all supported languages.
=> Add write-through closing brackets for selected Kite completions.

lib/kite.js
Addresses Atom for kiteco/kiteco#10456 for the updated spec.
Essentially leveraged the second argument in `KiteAPI.getOnboardingFilePath` to pull language specific tutorial files. They don't yet exist so this change would at the moment create a warning notification. ~Should test and merge after those files get added to the endpoint.~ Should merge for release at JS public launch.
Check that:
1. Opening Atom with `kite.showWelcomeNotificationOnStartup: true` in atom's `config.cson` and `"has_done_onboarding": "false"` in `~/.kite/settings.json` attempts to open the Python onboarding file. (no regression)
2. Commands for `Kite: Go Tutorial` and `Kite: Javascript Tutorial` are present in the command palette. (Note that these will fail to pull an onboarding file from kited at the moment as …
=> Atom Onboarding with Command Palette

README.md, package.json
cc @caelan-kite 
trigger fingers. I think it makes more sense to sit on these until launch day morning and then release them.
=> Revert "Revert "Atom plugin description updates""

README.md
- `Kite: Tutorial` updated to language-specific tutorials
- Moved autocomplete to top
- Added `(Python only)` to feature headers
=> Update commands and label Python-only features

lib/kite.js
Addresses https://github.com/kiteco/kiteco/issues/11202 for Atom
This should apply to all snippets from all providers because we patch autocomplete-plus's snippets manager to insert our own behavior (cc @edzkite is this true based off your understanding?).
The regex is a bit nasty. We could potentially return a flag from kited instead, but thought I'd get this out for discussion to see if we want to address on-select completions in-editor vs kited for Atom first. Unsure if we always return `1` for the first one/whether to rely on that if we think regex is ok for this.
This will request completions when selecting `len(filter${1:})$0`. Not sure if that's what we want either.
=> Remove completion request on placeholder selection

lib/completions.js
This improves the performance of `get suggestions list element` by caching the values related to autocomplete-plus.
Previously Kite was calling quite expensive API such as `atom.packages.getAvailablePackageNames` on every single keystroke. This has caused the performance of the text editor to be reduced.
This PR fixes this issue by caching the result. This 620ms is completely gone now
=> Improve the performance of get suggestions list element 

lib/codenav.js, package.json
`atom.packages.getApmPath()` returns the `apm` path of the editor install.
=> Send Editor Path In Related Code Request

lib/editors.js
Adds support for the `.pyw` Python extension. Required for https://github.com/kiteco/kiteco/pull/12167
=> Add .pyw to Python extensions.

lib/codenav.js, lib/notifications-center.js
Atom portion of https://github.com/kiteco/kiteco/issues/12248
In addition to removing empty line checks:
- Cleaned up `getRelatedCodeErrHandler`
- Fix error handling when there's no active text editor
=> Related Code Error Handling Improvements

lib/codenav-decoration.js, lib/elements/kite-codenav-button.js, lib/elements/kite-logo.js, lib/kite.js, package.json, styles/kite-decoration.less
Addresses https://github.com/kiteco/kiteco/issues/11934 for Atom
- Added a click-able line decoration for predictive navigation when it's enabled
@its-dhung Lmk how this looks, changes you'd make, or if you want to take a pass on the styling
=> Codenav line decoration

lib/codenav-decoration.js
Addresses https://github.com/kiteco/kiteco/issues/12335 for Atom
The decoration here behaves differently from VSCode's in that it does not disappear when navigating with the keyboard. This is because Atom's API does not expose a 'source' of the cursor change like VSCode does.
=> Hide Line Decoration During Typing

lib/elements/kite-status-panel.js, spec/elements/kite-status-panel-spec.js, styles/kite-status-panel.less
Addresses https://github.com/kiteco/kiteco/issues/12288 's status panel for Atom
- Main use case is for the `all_features_pro` button and text but since I needed specific alignment,
- Refactored various statuses to make things more uniform
The login button is suppressed when the status sends over a button. Periods indicate splitting (`Locked until tomorrow. Upgrade now to unlock.`). The spec had the button on the left, though most of Atom's buttons are on the right. I think this looks nice though.
If a button isn't sent but a message with periods is sent, we'd get something like this, though currently we only send a message with a period with this particular status and we always send a button with it as well. Separately, IMO the login button looks misplaced here and other mockups, but not …
=> Status Panel Button And Styling

lib/kite.js
All of the Tree-sitter issues were fixed a year ago back in Atom 1.40.
Fixes #699
=> Remove tree-sitter workaround
