.gitignore
lib/completions.js
lib/events.js
lib/kite.js
lib/ready.js
package.json

🚧 **This is still a work in progress** 🚧 
I tried to make each commit as simple as I could, many can probably be cherry-picked but I'm not sure that there won't be any conflicts on some.
I'll probably also look at how refactor the code to get rid of all the boilerplate for notifications and such.

Code review

---

lib/completions.js
lib/elements/login.js
lib/elements/status.js
lib/events.js
lib/kite.js
lib/localconfig.js
lib/metrics.js
lib/ready.js
lib/utils.js
package.json

For older JS engines:
* adds `'use strict'` to source files
* removes default args

compatibility for older JS engines

---

keymaps/kite.cson
lib/elements/login.js
styles/login.less

Includes changing the login panel class name to have a more specific
name
Ref #16

Fix native key bindings in login form

---

.eslintignore
.eslintrc.js
.gitignore
lib/completions.js
lib/constants.js
lib/elements/login.js
lib/elements/status.js
lib/events.js
lib/kite.js
lib/localconfig.js
lib/metrics.js
lib/ready.js
lib/utils.js
package.json

Includes fixing all the linter warnings and errors and extracting constants into a specific file.

Add eslint

---

lib/elements/html-utils.js
lib/elements/kite-expand-function.js
lib/elements/kite-expand-module.js
lib/elements/kite-open-link.js
lib/kite-data-utils.js
styles/kite-expand-navigation.less
styles/kite-expand.less
styles/kite-hover.less
styles/kite-open-link.less
styles/variables.less

@abe33 cc @adamsmith 
Some design tweaks as part of a design iteration:
- Added small padding to section contents
- Changed design of *Usages* section
- Changed design of the footer
- Small changes to sizes, paddings, and colors. 
Also added comments at https://kite.quip.com/acH6ATLLWrDE

Style tweaks

---

lib/kite-app.js
lib/kite.js
lib/metrics-center.js
package.json
spec/kite-spec.js

Display install flow on account creation step if kite isn't installed

---

lib/elements/kite-hover.js
styles/kite-hover.less

@abe33 cc @adamsmith 
Some small tweaks to hover + branding

Small tweaks + branding

---

lib/elements/kite-signature.js
styles/content.less
styles/kite-signature.less

@abe33 
Some small design tweaks :)

Small design tweaks

---

lib/elements/html-utils.js
lib/elements/kite-signature.js
lib/plan.js

- getting key from plan for usages `usage_editor` - > `usages_editor`
- getting key from plan for call_signatures `call_signatures` -> `call_signatures_editor`
- include `localtoken` in requests to `plan` endpoint

Minor pro plan gate fixes

---

lib/data-loader.js
styles/kite-signature.less
styles/kite.less

@abe33 
Just some tiny style fixes
- Additional margin between more link and logo opacity
- Smaller size of logo and font of signature completions bottom right

Small style fixes

---

lib/elements/html-utils.js
spec/fixtures/sample.py
styles/content.less

Hide parameters when no documentation and allow signature wrapping

---

lib/elements/html-utils.js
styles/content.less

@abe33 Just some usages design changes and trimming leading whitespace in usage code.

Small usages design bits

---

lib/elements/kite-links.js
lib/elements/kite-signature.js
lib/kite-data-utils.js
package.json
styles/kite-signature.less

Display kwargs in signature panel

---

lib/elements/html-utils.js
lib/elements/kite-expand-function.js
lib/elements/kite-hover.js
lib/elements/kite-signature.js
lib/elements/kite-tour.js
lib/elements/navigable-panel.js
lib/kite-data-utils.js
lib/utils.js
package.json
spec/elements/kite-curated-example-spec.js
spec/elements/kite-expand-function-spec.js
spec/elements/kite-hover-spec.js
spec/fixtures/sample.py
spec/kite-app-spec.js
spec/overlay-manager-spec.js
styles/content.less
styles/kite-signature.less

Feature design pass

---

lib/kite-editor.js
lib/kite.js

Allow events for all editors

---

lib/kite.js
package.json

Change kite tour display default

---

lib/data-loader.js
lib/elements/html-utils.js
lib/elements/kite-active-search.js
lib/elements/kite-open-link.js
lib/elements/navigable-panel.js
lib/kite-editor.js
lib/kite.js
lib/metrics.js
lib/urls.js
spec/fixtures/sample.py

New feature metrics

---

lib/elements/navigable-panel.js
spec/fixtures/sample with space.py

Use symbol endpoint when showing members details

---

lib/data-loader.js
lib/elements/html-utils.js
lib/elements/kite-expand-function.js
lib/elements/kite-expand-instance.js
lib/elements/kite-expand-module.js
lib/elements/navigable-panel.js
lib/elements/sticky-title.js
lib/kite-data-utils.js
spec/data-loader-spec.js
spec/elements/kite-expand-function-spec.js
spec/fixtures/test/increment-symbol.json
spec/fixtures/test/increment-value.json

Use symbol endpoint in sidebar

---

lib/kite.js
package.json
spec/spec-helpers.js

Now all the requests made to `kited` will be available in the network panel of chromium's devtools.

Debug in devtools

---

lib/elements/kite-active-search.js
lib/elements/navigable-panel.js
lib/modes/sidebar.js

Make active search use the value endpoint instead of the symbol one

---

lib/elements/function-utils.js
lib/elements/html-utils.js
lib/elements/kite-expand-function.js
lib/elements/kite-expand-instance.js
lib/elements/kite-expand-module.js
lib/elements/sticky-title.js
lib/kite-app.js
lib/kite-data-utils.js
package.json
spec/elements/kite-expand-function-spec.js
styles/content.less
styles/kite-active-search.less

Fix plugin behaviour

---

lib/kite-app.js
spec/kite-app-spec.js

Fix reset email password link

---

lib/elements/html-utils.js
lib/elements/kite-active-search.js
lib/elements/kite-curated-example.js
lib/elements/kite-expand-function.js
lib/elements/kite-expand-instance.js
lib/elements/kite-expand-module.js
lib/elements/kite-expand-panel.js
lib/elements/kite-login.js
lib/elements/kite-open-link.js
lib/elements/kite-sidebar.js
lib/elements/navigable-stack.js
lib/kite-app.js
lib/notifications-center.js
package.json
spec/elements/kite-expand-function-spec.js
spec/elements/kite-login-spec.js
spec/fixtures/sample.py
spec/notifications-center-spec.js
styles/content.less
styles/kite-active-search.less
styles/kite-login.less
styles/kite-open-link.less
styles/kite-sidebar.less

As described in kiteco/kiteco#5075

UI changes

---

lib/editor-events.js

Prevent focus event from being sent on each click

---

lib/elements/kite-localtoken-anchor.js
lib/elements/kite-status-panel.js
lib/kite.js
lib/notifications-center.js
spec/elements/kite-status-panel-spec.js
spec/notifications-center-spec.js

Replace all calls to `http://localhost:46624/settings` and sub routes with calls to `kite://settings`.

Change status settings url

---

lib/elements/kite-status-panel.js
lib/kite.js
lib/notifications-center.js
spec/elements/kite-status-panel-spec.js
spec/notifications-center-spec.js

Reverts kiteco/atom-plugin#315

Revert "Change status settings url"

---

lib/kite.js

It should help reducing the activation time if the process to connect to kited takes more time than usual.
Ref #319

Do not return the connection promise in activate

---

lib/data-loader.js
lib/elements/kite-autocorrect-sidebar.js
lib/kite-editor.js
lib/kite.js
lib/metrics.js
lib/urls.js
spec/autocorrect-spec.js
spec/fixtures/autocorrect-fixed-no-fixes.json
spec/fixtures/autocorrect-fixed-with-fixes.json
spec/fixtures/autocorrect-hash-mismatch.json
spec/fixtures/autocorrect-no-fixes.json
spec/fixtures/errored.py
styles/kite-autocorrect-sidebar.less

This PR covers the support for hash mismatch feedback as well as the thumb up/down feedbacks.

Autocorrect improvements

---

lib/data-loader.js

Remove def link in completions description

---

lib/elements/kite-autocorrect-sidebar.js

 Reverse feedback hands and all tooltips to them. 

---

lib/completions.js
lib/kite.js

Remove events for unsupported files

---

lib/elements/kite-autocorrect-sidebar.js

Fix bug in autocorrect sidebar when switching to a non-editor tab

---

lib/elements/kite-active-search.js
lib/urls.js

Change search endpoint

---

lib/elements/kite-autocorrect-sidebar.js
styles/kite-autocorrect-sidebar.less

@abe33
This builds on your branch. Hope you can integrate somehow?

Autocorrect styling fixes.

---

lib/elements/kite-autocorrect-sidebar.js
lib/kite.js

Name change to error rescue.

---

lib/elements/kite-autocorrect-sidebar.js
package.json
spec/autocorrect-spec.js
styles/kite-autocorrect-sidebar.less

@abe33
· baseline alignment for options
· thumbs up/down from Octoicons, better visibility on light bk
· swapped question mark for info
· better highlight for thumbs up when clicking around
· diff style and fixed +/– positioning

Last batch of UI fixes.

---

lib/elements/kite-autocorrect-sidebar.js
styles/kite-autocorrect-sidebar.less

@dbratz1177 
· error rescue » Error Rescue
· somehow the icon markup and style got out of sync 
· change the input type from a checkbox to a toggle (styling went through, but the actual change was somehow lost in a merge before)

Tiny last-second AutoCorrect fixes.

---

lib/elements/kite-autocorrect-sidebar.js

Switch the AC help URL to the final doc.

---

lib/elements/kite-sidebar.js
lib/kite.js

Otherwise it just fallback to the editor command.

Make sure to only trigger sidebar openInWeb if there's a link

---

lib/data-loader.js

fixes https://github.com/kiteco/kiteco/issues/5600

makes completions footer work

---

lib/elements/kite-search.js

fixes #5653 and #5603 (in kiteco)

fixes bug with expand panel

---

lib/kite.js

Note: I dangerously did a string change.  I did not test this.
as discussed with Marcin

Change welcome message to be more friendly

---

lib/completions.js

Remove memoization mecanism

---

lib/metrics.js

Do not throw error if mac address can't be found

---

lib/elements/kite-status.js

See https://rollbar.com/Kite/Atom/items/2254/

Guard against missing editor of a kite editor in status

---

README.md
lib/kite.js
menus/kite.cson

Standardize commands

---

lib/elements/html-utils.js
lib/elements/kite-error-rescue-sidebar.js
lib/elements/kite-expand-panel.js
lib/elements/kite-status-panel.js
lib/elements/kite-status.js
styles/content.less
styles/kite-error-rescue-sidebar.less
styles/kite-sidebar.less
styles/kite-status.less

Fixes some UI issues identified by @mwichary, as well as a download linking issue

Some minor fixes

---

lib/elements/kite-links.js
lib/elements/kite-status-panel.js
lib/link-scheme.js
lib/notifications-center.js
spec/elements/kite-status-panel-spec.js
spec/notifications-center-spec.js

Replace remaining use of localhost to access sidebar settings route

---

lib/gestures/word-hover.js

Deactivate word gesture when the mouse leave the window

---

README.md

Use URLs to raw images on github in README

---

package.json

Includes new fallback for windows install path

Bump kite-installer

---

lib/overlay-manager.js

Prevent calls to overlay APIs with no editor nor position

---

lib/kite.js

Implement starting and stopping counters

---

lib/urls.js
spec/fixtures/josé/sample.py
spec/urls-spec.js

Fix missing uri encoding in authorized url

---

lib/elements/function-utils.js
lib/elements/kite-expand-function.js
lib/elements/kite-expand-module.js

Use symbol name instead of repr for popular patterns

---

lib/kite-modal.js
lib/kite-notification.js
lib/kite.js
lib/notification-queue.js
lib/notifications-center.js
spec/error-rescue-spec.js
spec/notification-queue-spec.js
spec/notifications-center-spec.js
spec/spec-helpers.js

Includes moving the kite queue and startup notification to the center
and implement events from notification to queue to center.

Switch notification center to use a queue for all notifications

---

lib/kite.js

Patch autocomplete to not trigger completion after 1 char insert

---

lib/elements/kite-status-panel.js
spec/elements/kite-status-panel-spec.js

Change labels for trial in status panel

---

lib/kite.js

Change url to open copilot

---

lib/kite.js

:bug: Fix suggestions list showing up after confirming a one char suggestion

---

lib/completions.js

Fix replacementPrefix when it's a space

---

lib/kite.js
spec/json-runner-spec.js

Fix broken filter with pane items with no URI

---

lib/elements/kite-status-panel.js
lib/notifications-center.js
spec/elements/kite-status-panel-spec.js

Dismiss whitelist notification when whitelisting from the status panel

---

lib/completions.js
spec/fixtures/sample.py

They were messing up the whole check of being inside a signature.
Closes #415

Remove custom signature detection rules

---

lib/completions.js

Prevent duplicate insertion when completion text matches prefix

---

lib/notifications-center.js

Guard against undefined dismiss function

---

package.json

Because people are still breaking stuff with patch releases...

Fix getmac version

---

lib/completions.js

Allow , and ' ' to trigger signature with cursor in closing paren

---

README.md
lib/data-loader.js
lib/elements/kite-hover.js
lib/elements/kite-links.js
lib/elements/kite-signature.js
lib/kite-editor.js
lib/urls.js

Remove kite com links

---

lib/kite.js
spec/kite-spec.js

Implement tree-sitter warning notification

---

lib/kite.js
spec/fixtures/completions.json
spec/fixtures/json.py
spec/fixtures/sample.py
spec/signature-plus-completions-spec.js
styles/kite.less

Keep signature visible on suggestion confirmation

---

styles/kite-hover.less
styles/kite.less

• Makes hover type container text vertically centered
• Fixes padding in the completions UI to preserve scrolling but also don't truncate content

Minor stylistic changes

---

lib/kite.js

Add some delay to reload in tree-sitter notification

---

lib/kite.js
lib/metrics.js

Remove health metrics

---

lib/kite.js
lib/notifications-center.js

updates the live onboarding flow to be more in line with the updated [spec](https://kite.quip.com/TmZJAhr5XdC4/Plugin-Live-Onboarding-Spec)
cc @dhung09

live onboarding updates

---

lib/kite.js

Hide autocomplete-python results when showing signature after open paren

---

lib/kite.js
package.json
spec/kite-spec.js

Implement kited autostart

---

lib/editor-events.js
lib/kite-editor.js

* Fixes #542
* Fixes this traceback on startup:

Fix tracebacks

---

lib/elements/kite-hover.js
lib/elements/kite-links.js
lib/elements/kite-logo.js
lib/elements/kite-open-link.js
lib/elements/kite-search.js
lib/elements/kite-signature.js
lib/elements/kite-status-panel.js
lib/elements/kite-status.js

A long due change, now all elements use the new v1 API.

Use v1 custom element for all elements

---

.eslintrc.js
lib/elements/kite-signature.js

Use resize observer and adjust signature max-width to fit container

---

lib/completions.js
lib/kite.js
lib/notifications-center.js
package.json

* Removes the health metrics notification (Fixes #561)
* Removes the editor vacancies notification
* Don't show welcome notification if onboarding file is shown
* Remove unused settings

Clean up notifications and settings

---

lib/editor-events.js
package.json

additionally bumps `kite-installer` version - I was getting an error related to an outdated version of `kite-connect` otherwise

fixes #568

---

lib/elements/kite-hover.js
lib/elements/kite-links.js
lib/elements/kite-status-panel.js
lib/kite-app.js
lib/kite-data-utils.js
lib/overlay-manager.js
spec/elements/kite-hover-spec.js
spec/elements/kite-status-panel-spec.js
spec/status-spec.js
styles/kite-hover.less

addresses 3 of the issues mentioned [here](https://kite.quip.com/aSWPAxHqAe9o) (hover instance type, hover over signature and completions panel, status panel hiding), and additionally fixes some lingering test failures
fixes #385

Hover instance kind

---

assets/logo-completions.svg
lib/data-loader.js
lib/elements/kite-hover.js
lib/elements/kite-signature.js
lib/kite-data-utils.js
package.json
styles/content.less
styles/kite-completions.less
styles/kite-curated-example.less
styles/kite-error-rescue-sidebar.less
styles/kite-hover.less
styles/kite-links.less
styles/kite-logo.less
styles/kite-signature.less
styles/kite.less

Addresses the remaining issues described here: https://kite.quip.com/aSWPAxHqAe9o
General efforts were applied to making the Atom UI less intrusive, more space efficient, more consistent across elements, and more parseable visually
More specifically:
- padding, margins, and font-sizes were reduced across signature, completions, and hover elements 
- the hover UI is now restricted to a single line
- unicode icons were introduced to aid with the parsing of what certain actions do
- some code was opportunistically reorganized
- return types were added to signatures
- popular patterns are now collapsable (ala Sublime)

Minimize screen real estate

---

lib/elements/kite-hover.js
lib/elements/kite-links.js
lib/kite-data-utils.js
lib/utils.js

Addresses, in part, https://github.com/kiteco/kiteco/issues/7139
In implementing this, I ran into https://github.com/kiteco/kiteco/issues/7711. This implementation works for global symbols
@edzkite - I'm going to start pinging you on Atom related PRs to help you get ramped up on the codebase

docs links to webdocs

---

lib/utils.js

stray log that was getting run a decent amount

scrubs log

---

lib/elements/kite-signature.js

fixes inconsistent doc link issue from QA
finishes up what this started: https://github.com/kiteco/atom-plugin/pull/586

fixes issue

---

lib/data-loader.js
styles/kite-completions.less

PR for Snippets UI adjustements as listed in https://kite.quip.com/C54RA6oZYU3l

Snippets UI Fine Tuning

---

lib/data-loader.js

Sends `offset_encoding` param to KiteAPI.
Endpoint checklist:

Send offset_encoding to KiteAPI

---

dist/main.js
lib/kite.js

Fixes #602 
KiteAPI PR: https://github.com/kiteco/kite-api-js/pull/24

Pass in editor ID to onboarding_file endpoint

---

lib/kite-data-utils.js

Resolves https://github.com/kiteco/kiteco/issues/8087

Use web_id in Docs link for snippets

---

lib/kite.js

Fixes #612.
Besides the actual logic, please let me know if the docs I added could be improved.

Completion Loop Fix

---

lib/constants.js

Fixes https://github.com/kiteco/kiteco/issues/8204

Change file size limit to 75KB

---

lib/constants.js
lib/kite-data-utils.js

Fixes https://github.com/kiteco/kiteco/issues/8589
Formatter updated a bunch of whitespace.
Relevant change: https://github.com/kiteco/atom-plugin/compare/icon-fix?expand=1#diff-82032542039d0072e7c056f672bb69f1R334
Tested locally.

Default to unknown type if completion.hint is null or empty

---

lib/elements/kite-status-panel.js
lib/status.js

Relevant changes:
- https://github.com/kiteco/atom-plugin/compare/status-update?expand=1#diff-0236e9ad89cb02cd990eabd968e1291dR329
- https://github.com/kiteco/atom-plugin/compare/status-update?expand=1#diff-9971595d5358d9bfdac4915f7b22664bR131

Update Kite statuses

---

README.md

Adding copy updates for the `atom-plugin` repo with links to new webpages.
cc @adamsmith - I'm starting to open these PRs

atom-plugin repo README copy updates

---

dist/main.js
lib/urls.js
spec/signature-plus-completions-spec.js

Fixes https://github.com/kiteco/kiteco/issues/9418

Remove references to deprecated completions endpoints

---

lib/editors.js
lib/kite.js
lib/notifications-center.js
package.json

Resolves https://github.com/kiteco/kiteco/issues/9913
Hold on:
before merging.

Add Go Beta Notification

---

dist/main.js
lib/editors.js
lib/kite.js
lib/notifications-center.js
package.json

Resolves https://github.com/kiteco/kiteco/issues/10000

Add Kite JS Beta Notification

---

dist/main.js
lib/editors.js
lib/kite.js
lib/notifications-center.js
package.json

This reverts commit 6f853383e29214352deca7da5a5374962208ada6.
Given we haven't publicly released JS yet, reverting this commit in master. Will re-merge pre-launch.

Revert "Add Kite JS Beta Notification (#646)"

---

README.md
package.json

settings.json and README updates ahead of launch.

Atom plugin description updates

---

README.md
package.json

Reverts kiteco/atom-plugin#667

Revert "Atom plugin description updates"

---

lib/editors.js
lib/kite-app.js

add all-language-lexical languages

---

lib/notifications-center.js

Atom implementation of kiteco/kiteco#12098.

Handle ErrPathHasUnsupportedExtension

---

lib/codenav.js
lib/docs.js
lib/kite.js
lib/notifications-center.js

Addresses https://github.com/kiteco/kiteco/issues/12288 for Atom
- Added notification error handler that reads and shows a notification if it exists
- Refactored the docs command and related logic to live with the hover provider in `lib/docs.js`

All Feat Pro Notification

---

lib/kite-app.js
lib/notifications-center.js
lib/status.js

Implements updated [spec](https://kite.quip.com/VGaAAdpgwvnc/Spec-Editor-Plugin-Install-Flow)
As part of this change, the status bar will always be visible for non-supported files and while installing. 
Once Kite is installed, the status bar will be invisible if there's no active window with a filename.

Add Prompt Before Installation
